"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { content } from "@/data/content";
import { useRevealOnScroll } from "@/hooks/use-reveal-on-scroll";
import styles from "./memory-gallery.module.css";

function Photo({ memory, large = false }: { memory: typeof content.memories[number]; large?: boolean }) {
  return memory.imageSrc ? <Image src={memory.imageSrc} alt={memory.imageAlt} fill sizes={large ? "(max-width: 700px) 92vw, 42rem" : "(max-width: 700px) 92vw, 30vw"} className={styles.image} style={{ objectPosition: memory.objectPosition }} /> : <div className={`${styles.placeholder} ${styles[memory.accent]}`} aria-hidden="true"><span>♥</span><small>Tu recuerdo aquí</small></div>;
}
export function MemoryGallery() {
  const { ref, visible } = useRevealOnScroll<HTMLElement>(); const [selected, setSelected] = useState<number | null>(null); const opener = useRef<HTMLButtonElement | null>(null); const dialog = useRef<HTMLDivElement>(null);
  const close = () => { setSelected(null); requestAnimationFrame(() => opener.current?.focus()); };
  useEffect(() => { if (selected === null) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; const keys = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key === "ArrowLeft") setSelected((i) => i === null ? i : (i + content.memories.length - 1) % content.memories.length); if (event.key === "ArrowRight") setSelected((i) => i === null ? i : (i + 1) % content.memories.length); if (event.key === "Tab") { const items = dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled])'); if (!items?.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; window.addEventListener("keydown", keys); const firstButton = dialog.current?.querySelector<HTMLElement>("button"); firstButton?.focus(); return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", keys); }; }, [selected]);
  return <><section id="recuerdos" ref={ref} className={`${styles.section} ${visible ? styles.visible : ""}`} aria-labelledby="memories-title"><header className={styles.header}><p>{content.bridge.eyebrow}</p><h2 id="memories-title">{content.bridge.title}<span>{content.bridge.continuation}</span></h2><div>{content.bridge.description}</div></header><div className={styles.grid}>{content.memories.map((memory, index) => <button key={memory.id} type="button" className={styles.card} style={{ "--rotation": `${memory.rotation}deg`, "--delay": `${index * 70}ms` } as React.CSSProperties} onClick={(event) => { opener.current = event.currentTarget; setSelected(index); }}><div className={styles.photo}><Photo memory={memory} /></div><h3>{memory.title}</h3><p>{memory.caption}</p><span className={styles.open}>Ver recuerdo <b>↗</b></span></button>)}</div></section>{selected !== null && <div className={styles.backdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><div ref={dialog} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="memory-viewer-title"><button type="button" className={styles.close} onClick={close} aria-label="Cerrar recuerdo">×</button><div className={styles.viewerPhoto}><Photo memory={content.memories[selected]} large /></div><p className={styles.counter}>{selected + 1} de {content.memories.length}</p><h2 id="memory-viewer-title">{content.memories[selected].title}</h2><p className={styles.viewerCaption}>{content.memories[selected].caption}</p><div className={styles.controls}><button type="button" onClick={() => setSelected((selected + content.memories.length - 1) % content.memories.length)}>← Anterior</button><button type="button" onClick={() => setSelected((selected + 1) % content.memories.length)}>Siguiente →</button></div></div></div>}</>;
}
